package tools.jackson.module.blackbird.codegen;

import java.lang.classfile.ClassFile;
import java.lang.classfile.CodeBuilder;
import java.lang.classfile.Label;
import java.lang.classfile.attribute.MethodParameterInfo;
import java.lang.classfile.attribute.MethodParametersAttribute;
import java.lang.classfile.instruction.SwitchCase;
import java.lang.constant.ClassDesc;
import java.lang.constant.ConstantDescs;
import java.lang.constant.DynamicConstantDesc;
import java.lang.constant.MethodTypeDesc;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Optional;

import tools.jackson.core.JsonParser;
import tools.jackson.core.JsonToken;
import tools.jackson.core.sym.PropertyNameMatcher;
import tools.jackson.databind.DeserializationContext;
import tools.jackson.databind.ValueDeserializer;
import tools.jackson.databind.deser.SettableBeanProperty;
import tools.jackson.databind.deser.ValueInstantiator;
import tools.jackson.databind.deser.bean.BeanDeserializerBase;
import tools.jackson.databind.util.ClassUtil;
import tools.jackson.module.blackbird.internal.GeneratedReaderBase;

/**
 * Emits a hidden-class deserializer for one bean: a loop on nextNameMatch, a
 * tableswitch on the property index, inlined scalar reads for eligible
 * properties, and the stock SettableBeanProperty (a named classData constant)
 * for everything else. Member access and construction go through constant
 * MethodHandles with erased descriptors (see {@link MemberHandles}), so the
 * generated bytecode never names the bean class and every codec defines in
 * the module's own context, whatever the bean's package, module, or
 * classloader.
 */
public final class BeanReaderGenerator
{
    public enum Kind { STRING, INT, LONG, BOOLEAN, CHILD, STOCK }

    // How a generated codec treats an active view. NONE: views cannot affect
    // this bean (the stock (de)serializer would ignore them too), no view code.
    // DELEGATE: an active view hands the whole call to the stock fallback
    // (beans with more than 64 properties). MASK: the codec resolves a cached
    // per-view visibility bitmask and each property arm tests its bit, so
    // view-active calls keep the generated fast path.
    public enum ViewStrategy { NONE, DELEGATE, MASK }

    // handle stores the value into the bean: (Object, eV)void in POJO mode,
    // (Object, eV)Object in builder mode (the returned builder is kept), and
    // null in record mode (values collect into locals) and for STOCK arms.
    // type is the record component type in record mode and the child value
    // type for CHILD; child is the linked generated codec for CHILD.
    public record GenProp(String name, Kind kind, SettableBeanProperty stock,
            Class<?> type, GeneratedReaderBase child, MethodHandle handle) {
        public GenProp(String name, Kind kind, SettableBeanProperty stock) {
            this(name, kind, stock, null, null, null);
        }

        public GenProp(String name, Kind kind, SettableBeanProperty stock, Class<?> type) {
            this(name, kind, stock, type, null, null);
        }
    }

    private static final ClassDesc CD_JSON_PARSER = Descs.of(JsonParser.class);
    private static final ClassDesc CD_JSON_TOKEN = Descs.of(JsonToken.class);
    private static final ClassDesc CD_DESER_CONTEXT = Descs.of(DeserializationContext.class);
    private static final ClassDesc CD_NAME_MATCHER = Descs.of(PropertyNameMatcher.class);
    private static final ClassDesc CD_SETTABLE_PROP = Descs.of(SettableBeanProperty.class);
    private static final ClassDesc CD_BASE = Descs.of(GeneratedReaderBase.class);
    private static final ClassDesc CD_BEAN_DESER_BASE = Descs.of(BeanDeserializerBase.class);
    private static final ClassDesc CD_ISE = Descs.of(IllegalStateException.class);

    private static final MethodTypeDesc MTD_NEXT_NAME_MATCH =
            MethodTypeDesc.of(ConstantDescs.CD_int, CD_NAME_MATCHER);
    private static final MethodTypeDesc MTD_NEXT_TOKEN = MethodTypeDesc.of(CD_JSON_TOKEN);
    private static final MethodTypeDesc MTD_GET_STRING = MethodTypeDesc.of(ConstantDescs.CD_String);
    private static final MethodTypeDesc MTD_GET_INT = MethodTypeDesc.of(ConstantDescs.CD_int);
    private static final MethodTypeDesc MTD_GET_LONG = MethodTypeDesc.of(ConstantDescs.CD_long);
    private static final MethodTypeDesc MTD_GET_BOOLEAN = MethodTypeDesc.of(ConstantDescs.CD_boolean);
    private static final MethodTypeDesc MTD_ASSIGN_CURRENT =
            MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_Object);
    private static final MethodTypeDesc MTD_DESERIALIZE_AND_SET = MethodTypeDesc.of(
            ConstantDescs.CD_void, CD_JSON_PARSER, CD_DESER_CONTEXT, ConstantDescs.CD_Object);
    private static final MethodTypeDesc MTD_DESERIALIZE =
            MethodTypeDesc.of(ConstantDescs.CD_Object, CD_JSON_PARSER, CD_DESER_CONTEXT);
    private static final ClassDesc CD_SET = ConstantDescs.CD_Set;
    private static final MethodTypeDesc MTD_CTOR4 = MethodTypeDesc.of(ConstantDescs.CD_void,
            CD_BEAN_DESER_BASE, ConstantDescs.CD_boolean, CD_SET, CD_SET);
    private static final MethodTypeDesc MTD_HANDLE_UNKNOWN = MethodTypeDesc.of(
            ConstantDescs.CD_void, CD_JSON_PARSER, CD_DESER_CONTEXT, ConstantDescs.CD_Object);
    private static final MethodTypeDesc MTD_CHECK_SEEN = MethodTypeDesc.of(
            ConstantDescs.CD_void, CD_DESER_CONTEXT, ConstantDescs.CD_long, ConstantDescs.CD_int);
    private static final MethodTypeDesc MTD_GET_ACTIVE_VIEW =
            MethodTypeDesc.of(ConstantDescs.CD_Class);
    private static final MethodTypeDesc MTD_VIEW_MASK =
            MethodTypeDesc.of(ConstantDescs.CD_long, ConstantDescs.CD_Class);
    private static final MethodTypeDesc MTD_HIDDEN_VIEW = MethodTypeDesc.of(
            ConstantDescs.CD_void, CD_JSON_PARSER, CD_DESER_CONTEXT, CD_SETTABLE_PROP);
    private static final MethodTypeDesc MTD_VISIBLE_IN_VIEW =
            MethodTypeDesc.of(ConstantDescs.CD_boolean, ConstantDescs.CD_Class);
    private static final ClassDesc CD_EXCEPTION = ConstantDescs.CD_Exception;
    private static final MethodTypeDesc MTD_PROP_WRAP = MethodTypeDesc.of(
            Descs.of(RuntimeException.class), ConstantDescs.CD_Throwable,
            ConstantDescs.CD_Object, CD_SETTABLE_PROP, CD_DESER_CONTEXT);

    private static final MethodTypeDesc MTD_PROP_DESERIALIZE =
            MethodTypeDesc.of(ConstantDescs.CD_Object, CD_JSON_PARSER, CD_DESER_CONTEXT);
    private static final ClassDesc CD_VALUE_INSTANTIATOR =
            Descs.of(ValueInstantiator.class);
    private static final MethodTypeDesc MTD_CREATE_DEFAULT =
            MethodTypeDesc.of(ConstantDescs.CD_Object, CD_DESER_CONTEXT);
    private static final MethodTypeDesc MTD_DESER_SET_RETURN = MethodTypeDesc.of(
            ConstantDescs.CD_Object, CD_JSON_PARSER, CD_DESER_CONTEXT, ConstantDescs.CD_Object);
    private static final MethodTypeDesc MTD_NEW_INSTANCE =
            MethodTypeDesc.of(ConstantDescs.CD_Object);
    private static final MethodTypeDesc MTD_INJECT = MethodTypeDesc.of(
            ConstantDescs.CD_void, CD_DESER_CONTEXT, ConstantDescs.CD_Object);
    private static final MethodTypeDesc MTD_BUILD_INVOKE =
            MethodTypeDesc.of(ConstantDescs.CD_Object, ConstantDescs.CD_Object);

    // Generated code resolves class-data entries by NAME through the
    // classDataEntry bootstrap on the base class (the JDK classDataAt
    // bootstrap rejects any condy name but "_"); see dataName for the naming.
    private static final java.lang.constant.DirectMethodHandleDesc BSM_DATA_ENTRY =
            ConstantDescs.ofConstantBootstrap(CD_BASE, "classDataEntry", ConstantDescs.CD_Object);

    private BeanReaderGenerator() {}

    static void ldcData(CodeBuilder cob, String name, ClassDesc type) {
        cob.ldc(DynamicConstantDesc.ofNamed(BSM_DATA_ENTRY, name, type));
    }

    // The bean's short name without Class.getSimpleName(): that call consults
    // InnerClasses metadata, which raises IncompatibleClassChangeError for a
    // member class redefined in a foreign classloader, and such beans
    // accelerate. Class.getName() reads no metadata.
    static String codecName(Class<?> beanClass) {
        String name = beanClass.getName();
        return name.substring(name.lastIndexOf('.') + 1);
    }

    // Condy names are JVM unqualified names ('.', ';', '[', '/' forbidden) and
    // JSON property names are arbitrary, so sanitize and dedupe.
    static String dataName(Map<String, Object> data, String base) {
        StringBuilder sb = new StringBuilder(base.length());
        for (int i = 0; i < base.length(); i++) {
            char c = base.charAt(i);
            sb.append(c == '.' || c == ';' || c == '[' || c == '/' ? '$' : c);
        }
        String name = sb.toString();
        String candidate = name;
        for (int n = 2; data.containsKey(candidate); n++) {
            candidate = name + "$" + n;
        }
        return candidate;
    }

    // POJO mode: exactly one of defaultCtor (the no-arg constructor as a
    // ()Object handle) and instantiator is non-null. The instantiator covers
    // default creators that are not that constructor (a @JsonCreator factory,
    // a custom instantiator): the value comes from
    // ValueInstantiator.createUsingDefault, exactly like stock.
    public static ValueDeserializer<Object> generate(Class<?> beanClass, List<GenProp> props,
            PropertyNameMatcher matcher, BeanDeserializerBase fallback, MethodHandle defaultCtor,
            ValueInstantiator instantiator, ViewStrategy views, Ignorals ignorals,
            int[] aliasArms)
            throws ReflectiveOperationException {
        return generate(beanClass, props, matcher, fallback, defaultCtor, null, null,
                instantiator, views, ignorals, aliasArms);
    }

    // recordCtor non-null selects record mode: props are in canonical
    // constructor order, values collect into typed locals, and the erased
    // constructor MethodHandle ((e1..en)Object) builds the value.
    public static ValueDeserializer<Object> generate(Class<?> beanClass, List<GenProp> props,
            PropertyNameMatcher matcher, BeanDeserializerBase fallback, MethodHandle recordCtor,
            ViewStrategy views, Ignorals ignorals, int[] aliasArms)
            throws ReflectiveOperationException {
        return generate(beanClass, props, matcher, fallback, null, recordCtor, null, null,
                views, ignorals, aliasArms);
    }

    // builderSupport non-null selects builder mode: values apply to a builder
    // instance created by the stock ValueInstantiator through normalized
    // (Object, eV)Object setter handles, and the build MethodHandle
    // ((Object)Object) produces the value.
    public record BuilderSupport(ValueInstantiator instantiator, MethodHandle buildMethod) {}

    @SuppressWarnings("unchecked")
    public static ValueDeserializer<Object> generate(Class<?> beanClass, List<GenProp> props,
            PropertyNameMatcher matcher, BeanDeserializerBase fallback, MethodHandle defaultCtor,
            MethodHandle recordCtor, BuilderSupport builder, ValueInstantiator instantiator,
            ViewStrategy views, Ignorals ignorals, int[] aliasArms)
            throws ReflectiveOperationException {
        Map<String, Object> classData = new LinkedHashMap<>();
        classData.put("matcher", matcher);
        // Tier-A properties also carry their SettableBeanProperty: their
        // VALUE_NULL branch runs through it, since null handling is
        // configuration-dependent per property.
        String[] stockName = new String[props.size()];
        String[] childName = new String[props.size()];
        String[] handleName = new String[props.size()];
        for (int i = 0; i < props.size(); i++) {
            GenProp gp = props.get(i);
            stockName[i] = dataName(classData, gp.name() + "Prop");
            classData.put(stockName[i], gp.stock());
            if (gp.child() != null) {
                childName[i] = dataName(classData, gp.name() + "Codec");
                classData.put(childName[i], gp.child());
            }
            if (gp.handle() != null) {
                handleName[i] = dataName(classData, gp.name() + "Set");
                classData.put(handleName[i], gp.handle());
            }
        }
        if (defaultCtor != null) {
            classData.put("constructor", defaultCtor);
        }
        if (recordCtor != null) {
            classData.put("constructor", recordCtor);
        }
        if (builder != null) {
            classData.put("instantiator", builder.instantiator());
            classData.put("buildMethod", builder.buildMethod());
        }
        if (instantiator != null) {
            classData.put("instantiator", instantiator);
        }

        MethodHandles.Lookup definer = MethodHandles.lookup();
        // Records with injectables stay on the stock path (modifier gate), so
        // only the POJO and builder bodies consult this.
        boolean injectables = GeneratedReaderBase.hasInjectables(fallback);
        byte[] bytes = buildClass(definer.lookupClass().getPackageName(), beanClass, props,
                stockName, childName, handleName, recordCtor != null, builder != null,
                instantiator != null, injectables, views, aliasArms);
        CodegenDump.dump(beanClass, "reader", bytes);
        // No ClassOption.STRONG: the codec instance held by the mapper's
        // deserializer cache anchors the class, so codecs unload with the
        // mapper instead of pinning metaspace for the loader's lifetime.
        // Module-context defines never legitimately fail: any throw here is a
        // generator bug, surfaced through the placeholder's failure handling.
        MethodHandles.Lookup hidden = definer.defineHiddenClassWithClassData(
                bytes, Map.copyOf(classData), true);
        MethodHandle ctor = hidden.findConstructor(hidden.lookupClass(),
                MethodType.methodType(void.class, BeanDeserializerBase.class,
                        boolean.class, Set.class, Set.class));
        Ignorals ig = (ignorals == null) ? Ignorals.NONE : ignorals;
        try {
            return (ValueDeserializer<Object>) ctor.invoke(fallback,
                    ig.ignoreAllUnknown(), ig.ignorableProps(), ig.includableProps());
        } catch (Throwable t) {
            throw new IllegalStateException("cannot instantiate generated codec", t);
        }
    }

    /** Ignoral configuration carried from the modifier into the codec. */
    public record Ignorals(boolean ignoreAllUnknown, Set<String> ignorableProps,
            Set<String> includableProps) {
        public static final Ignorals NONE = new Ignorals(false, null, null);
    }

    private static byte[] buildClass(String targetPackage, Class<?> beanClass,
            List<GenProp> props,
            String[] stockName, String[] childName, String[] handleName,
            boolean recordMode, boolean builderMode, boolean instantiatorMode,
            boolean injectables, ViewStrategy views, int[] aliasArms) {
        // A hidden class must be named in its define context's package.
        ClassDesc thisClass = ClassDesc.of(
                targetPackage + ".BBReader_" + codecName(beanClass));
        return ClassFile.of().build(thisClass, clb -> {
            clb.withFlags(ClassFile.ACC_PUBLIC | ClassFile.ACC_FINAL | ClassFile.ACC_SUPER);
            clb.withSuperclass(CD_BASE);
            clb.withMethod(ConstantDescs.INIT_NAME, MTD_CTOR4, ClassFile.ACC_PUBLIC,
                    mb -> mb.with(params("fallback", "ignoreAllUnknown", "ignorableProps",
                                    "includableProps"))
                            .withCode(cob -> cob.aload(0).aload(1).iload(2).aload(3).aload(4)
                                    .invokespecial(CD_BASE, ConstantDescs.INIT_NAME, MTD_CTOR4)
                                    .return_()));
            clb.withMethod("deserialize", MTD_DESERIALIZE, ClassFile.ACC_PUBLIC,
                    mb -> mb.with(params("p", "ctxt")).withCode(cob -> {
                        if (builderMode) {
                            buildBuilderDeserialize(cob, props, stockName, childName,
                                    handleName, injectables, views, aliasArms);
                        } else if (!recordMode) {
                            buildDeserialize(cob, props, stockName, childName, handleName,
                                    instantiatorMode, injectables, views, aliasArms);
                        } else {
                            buildRecordDeserialize(cob, props, stockName, childName,
                                    views, aliasArms);
                        }
                    }));
            if (views == ViewStrategy.MASK) {
                emitComputeViewMask(clb, props, stockName);
            }
        });
    }

    // Debug metadata: parameter names and named locals make dumped codecs
    // (the blackbird.debug.dumpDir output) read like source in a decompiler;
    // the verifier ignores both attributes.
    static MethodParametersAttribute params(String... names) {
        MethodParameterInfo[] infos = new MethodParameterInfo[names.length];
        for (int i = 0; i < names.length; i++) {
            infos[i] = MethodParameterInfo.ofParameter(Optional.of(names[i]), 0);
        }
        return MethodParametersAttribute.of(infos);
    }

    // Overrides GeneratedReaderBase._computeViewMask: bit i set when arm i's
    // stock property is visible in the view, which keeps visibility semantics
    // (matchers, default-view inclusion) exactly the stock ones.
    private static void emitComputeViewMask(java.lang.classfile.ClassBuilder clb,
            List<GenProp> props, String[] stockName) {
        clb.withMethod("_computeViewMask", MTD_VIEW_MASK, ClassFile.ACC_PROTECTED,
                mb -> mb.with(params("activeView")).withCode(cob -> {
            final int maskSlot = 2;
            Label scopeStart = cob.newBoundLabel();
            cob.lconst_0().lstore(maskSlot);
            for (int i = 0; i < props.size(); i++) {
                Label skip = cob.newLabel();
                ldcData(cob, stockName[i], CD_SETTABLE_PROP);
                cob.aload(1);
                cob.invokevirtual(CD_SETTABLE_PROP, "visibleInView", MTD_VISIBLE_IN_VIEW);
                cob.ifeq(skip);
                cob.lload(maskSlot);
                cob.loadConstant(1L << i);
                cob.lor();
                cob.lstore(maskSlot);
                cob.labelBinding(skip);
            }
            cob.lload(maskSlot).lreturn();
            Label scopeEnd = cob.newBoundLabel();
            cob.localVariable(1, "activeView", ConstantDescs.CD_Class, scopeStart, scopeEnd);
            cob.localVariable(maskSlot, "mask", ConstantDescs.CD_long, scopeStart, scopeEnd);
        }));
    }

    // MASK strategy: resolves the visibility bitmask for the call (all-ones
    // when no view is active) into maskSlot.
    private static void emitViewMask(CodeBuilder cob, int ctxt, int maskSlot) {
        Label nullView = cob.newLabel();
        Label haveMask = cob.newLabel();
        cob.aload(ctxt).invokevirtual(CD_DESER_CONTEXT, "getActiveView", MTD_GET_ACTIVE_VIEW);
        cob.dup();
        cob.ifnull(nullView);
        cob.aload(0);
        cob.swap();
        cob.invokevirtual(CD_BASE, "_viewMask", MTD_VIEW_MASK);
        cob.lstore(maskSlot);
        cob.goto_(haveMask);
        cob.labelBinding(nullView);
        cob.pop();
        cob.loadConstant(-1L);
        cob.lstore(maskSlot);
        cob.labelBinding(haveMask);
    }

    // MASK strategy, start of each arm: a hidden property consumes its value
    // with stock semantics (advance to the value token, then the base helper
    // reports or skips) and continues the loop without touching the bean.
    private static void emitArmViewCheck(CodeBuilder cob, int parser, int ctxt, int maskSlot,
            int matcherSlot, int ixSlot, int armIndex, String stockName, Label loop) {
        Label visible = cob.newLabel();
        cob.lload(maskSlot);
        cob.loadConstant(1L << armIndex);
        cob.land();
        cob.lconst_0();
        cob.lcmp();
        cob.ifne(visible);
        // The fused match already advanced to the value token, so _hiddenView
        // consumes the current value without advancing.
        cob.aload(0).aload(parser).aload(ctxt);
        ldcData(cob, stockName, CD_SETTABLE_PROP);
        cob.invokevirtual(CD_BASE, "_hiddenView", MTD_HIDDEN_VIEW);
        nextNameMatch(cob, parser, matcherSlot, ixSlot);
        cob.goto_(loop);
        cob.labelBinding(visible);
    }

    private static void buildDeserialize(CodeBuilder cob,
            List<GenProp> props, String[] stockName, String[] childName, String[] handleName,
            boolean instantiatorMode, boolean injectables, ViewStrategy views, int[] aliasArms) {
        final int parser = 1;
        final int ctxt = 2;
        final int beanSlot = 3;
        final int matcherSlot = 4;
        final int ixSlot = 5;
        final int propSlot = 6;
        final int excSlot = 7;
        final int maskSlot = 8;
        Label propHandler = cob.newLabel();

        Label scopeStart = cob.newBoundLabel();
        Label delegate = emitEntryGuard(cob, parser, ctxt, views);
        if (views == ViewStrategy.MASK) {
            emitViewMask(cob, ctxt, maskSlot);
        }

        if (instantiatorMode) {
            ldcData(cob, "instantiator", CD_VALUE_INSTANTIATOR);
            cob.aload(ctxt);
            cob.invokevirtual(CD_VALUE_INSTANTIATOR, "createUsingDefault", MTD_CREATE_DEFAULT);
        } else {
            ldcData(cob, "constructor", ConstantDescs.CD_MethodHandle);
            cob.invokevirtual(ConstantDescs.CD_MethodHandle, "invokeExact", MTD_NEW_INSTANCE);
        }
        cob.astore(beanSlot);
        cob.aload(parser).aload(beanSlot)
           .invokevirtual(CD_JSON_PARSER, "assignCurrentValue", MTD_ASSIGN_CURRENT);
        if (injectables) {
            cob.aload(0).aload(ctxt).aload(beanSlot)
               .invokevirtual(CD_BASE, "_injectValues", MTD_INJECT);
        }

        ldcData(cob, "matcher", CD_NAME_MATCHER);
        cob.astore(matcherSlot);

        Label loop = cob.newLabel();
        Label switchPart = cob.newLabel();
        Label endObject = cob.newLabel();
        Label unknown = cob.newLabel();
        Label oddToken = cob.newLabel();
        Label defaultCase = cob.newLabel();

        emitFirstMatch(cob, parser, matcherSlot, ixSlot);

        cob.labelBinding(loop);
        cob.iload(ixSlot).ifge(switchPart);
        cob.iload(ixSlot).iconst_m1().if_icmpeq(endObject);
        cob.iload(ixSlot).ldc(-2).if_icmpeq(unknown);
        cob.goto_(oddToken);

        cob.labelBinding(switchPart);
        List<SwitchCase> cases = new ArrayList<>(props.size());
        Label[] caseLabels = new Label[props.size()];
        for (int i = 0; i < props.size(); i++) {
            caseLabels[i] = cob.newLabel();
            cases.add(SwitchCase.of(i, caseLabels[i]));
        }
        // Alias matcher indexes follow the primaries and share their arms.
        int totalNames = props.size() + ((aliasArms == null) ? 0 : aliasArms.length);
        for (int k = props.size(); k < totalNames; k++) {
            cases.add(SwitchCase.of(k, caseLabels[aliasArms[k - props.size()]]));
        }
        cob.iload(ixSlot);
        cob.tableswitch(0, totalNames - 1, defaultCase, cases);

        for (int i = 0; i < props.size(); i++) {
            cob.labelBinding(caseLabels[i]);
            if (views == ViewStrategy.MASK) {
                emitArmViewCheck(cob, parser, ctxt, maskSlot, matcherSlot, ixSlot, i,
                        stockName[i], loop);
            }
            Label armEnd = beginArm(cob, stockName[i], propSlot, propHandler);
            GenProp prop = props.get(i);
            switch (prop.kind()) {
                case STRING -> emitScalar(cob, beanSlot, parser, ctxt,
                        "getString", MTD_GET_STRING, ConstantDescs.CD_Object,
                        stockName[i], handleName[i], "VALUE_STRING", false);
                case INT -> emitScalar(cob, beanSlot, parser, ctxt,
                        "getIntValue", MTD_GET_INT, ConstantDescs.CD_int,
                        stockName[i], handleName[i], "VALUE_NUMBER_INT", false);
                case LONG -> emitScalar(cob, beanSlot, parser, ctxt,
                        "getLongValue", MTD_GET_LONG, ConstantDescs.CD_long,
                        stockName[i], handleName[i], "VALUE_NUMBER_INT", false);
                case BOOLEAN -> emitScalar(cob, beanSlot, parser, ctxt,
                        "getBooleanValue", MTD_GET_BOOLEAN, ConstantDescs.CD_boolean,
                        stockName[i], handleName[i], null, false);
                case CHILD -> emitChildArm(cob, beanSlot, parser, ctxt,
                        childName[i], stockName[i], handleName[i], false);
                case STOCK ->
                    // The fused match left the value token current; the stock
                    // property consumes it.
                    emitStockSet(cob, parser, ctxt, beanSlot, stockName[i]);
            }
            cob.labelBinding(armEnd);
            nextNameMatch(cob, parser, matcherSlot, ixSlot);
            cob.goto_(loop);
        }

        cob.labelBinding(defaultCase);
        throwIse(cob, "bad property index");

        cob.labelBinding(endObject);
        cob.aload(beanSlot).areturn();

        cob.labelBinding(unknown);
        cob.aload(0).aload(parser).aload(ctxt);
        cob.aload(beanSlot);
        cob.invokevirtual(CD_BASE, "_handleUnknown", MTD_HANDLE_UNKNOWN);
        nextNameMatch(cob, parser, matcherSlot, ixSlot);
        cob.goto_(loop);

        cob.labelBinding(oddToken);
        cob.aload(0).aload(parser).aload(ctxt)
           .invokevirtual(CD_BASE, "_unexpectedToken", MTD_DESERIALIZE)
           .areturn();

        emitPropertyHandler(cob, propHandler, ctxt, propSlot, excSlot, beanSlot);
        emitDelegateTail(cob, parser, ctxt, delegate);

        Label scopeEnd = cob.newBoundLabel();
        cob.localVariable(parser, "p", CD_JSON_PARSER, scopeStart, scopeEnd);
        cob.localVariable(ctxt, "ctxt", CD_DESER_CONTEXT, scopeStart, scopeEnd);
        cob.localVariable(beanSlot, "bean", ConstantDescs.CD_Object, scopeStart, scopeEnd);
        cob.localVariable(matcherSlot, "matcher", CD_NAME_MATCHER, scopeStart, scopeEnd);
        cob.localVariable(ixSlot, "ix", ConstantDescs.CD_int, scopeStart, scopeEnd);
        cob.localVariable(propSlot, "prop", CD_SETTABLE_PROP, scopeStart, scopeEnd);
        cob.localVariable(excSlot, "e", CD_EXCEPTION, scopeStart, scopeEnd);
        if (views == ViewStrategy.MASK) {
            cob.localVariable(maskSlot, "viewMask", ConstantDescs.CD_long, scopeStart, scopeEnd);
        }
    }

    private static void buildBuilderDeserialize(CodeBuilder cob,
            List<GenProp> props, String[] stockName, String[] childName, String[] handleName,
            boolean injectables, ViewStrategy views, int[] aliasArms) {
        final int parser = 1;
        final int ctxt = 2;
        final int builderSlot = 3;
        final int matcherSlot = 4;
        final int ixSlot = 5;
        final int propSlot = 6;
        final int excSlot = 7;
        final int maskSlot = 8;
        Label propHandler = cob.newLabel();

        Label scopeStart = cob.newBoundLabel();
        Label delegate = emitEntryGuard(cob, parser, ctxt, views);
        if (views == ViewStrategy.MASK) {
            emitViewMask(cob, ctxt, maskSlot);
        }

        ldcData(cob, "instantiator", CD_VALUE_INSTANTIATOR);
        cob.aload(ctxt);
        cob.invokevirtual(CD_VALUE_INSTANTIATOR, "createUsingDefault", MTD_CREATE_DEFAULT);
        cob.astore(builderSlot);
        // Injected values apply to the builder, like the stock builder-based
        // deserializer does before its property loop.
        if (injectables) {
            cob.aload(0).aload(ctxt).aload(builderSlot)
               .invokevirtual(CD_BASE, "_injectValues", MTD_INJECT);
        }

        ldcData(cob, "matcher", CD_NAME_MATCHER);
        cob.astore(matcherSlot);

        Label loop = cob.newLabel();
        Label switchPart = cob.newLabel();
        Label endObject = cob.newLabel();
        Label unknown = cob.newLabel();
        Label oddToken = cob.newLabel();
        Label defaultCase = cob.newLabel();

        emitFirstMatch(cob, parser, matcherSlot, ixSlot);

        cob.labelBinding(loop);
        cob.iload(ixSlot).ifge(switchPart);
        cob.iload(ixSlot).iconst_m1().if_icmpeq(endObject);
        cob.iload(ixSlot).ldc(-2).if_icmpeq(unknown);
        cob.goto_(oddToken);

        cob.labelBinding(switchPart);
        List<SwitchCase> cases = new ArrayList<>(props.size());
        Label[] caseLabels = new Label[props.size()];
        for (int i = 0; i < props.size(); i++) {
            caseLabels[i] = cob.newLabel();
            cases.add(SwitchCase.of(i, caseLabels[i]));
        }
        // Alias matcher indexes follow the primaries and share their arms.
        int totalNames = props.size() + ((aliasArms == null) ? 0 : aliasArms.length);
        for (int k = props.size(); k < totalNames; k++) {
            cases.add(SwitchCase.of(k, caseLabels[aliasArms[k - props.size()]]));
        }
        cob.iload(ixSlot);
        cob.tableswitch(0, totalNames - 1, defaultCase, cases);

        for (int i = 0; i < props.size(); i++) {
            cob.labelBinding(caseLabels[i]);
            if (views == ViewStrategy.MASK) {
                emitArmViewCheck(cob, parser, ctxt, maskSlot, matcherSlot, ixSlot, i,
                        stockName[i], loop);
            }
            Label armEnd = beginArm(cob, stockName[i], propSlot, propHandler);
            GenProp prop = props.get(i);
            switch (prop.kind()) {
                case STRING -> emitScalar(cob, builderSlot, parser, ctxt,
                        "getString", MTD_GET_STRING, ConstantDescs.CD_Object,
                        stockName[i], handleName[i], "VALUE_STRING", true);
                case INT -> emitScalar(cob, builderSlot, parser, ctxt,
                        "getIntValue", MTD_GET_INT, ConstantDescs.CD_int,
                        stockName[i], handleName[i], "VALUE_NUMBER_INT", true);
                case LONG -> emitScalar(cob, builderSlot, parser, ctxt,
                        "getLongValue", MTD_GET_LONG, ConstantDescs.CD_long,
                        stockName[i], handleName[i], "VALUE_NUMBER_INT", true);
                case BOOLEAN -> emitScalar(cob, builderSlot, parser, ctxt,
                        "getBooleanValue", MTD_GET_BOOLEAN, ConstantDescs.CD_boolean,
                        stockName[i], handleName[i], null, true);
                case CHILD -> emitChildArm(cob, builderSlot, parser, ctxt,
                        childName[i], stockName[i], handleName[i], true);
                case STOCK ->
                    emitStockSetReturn(cob, parser, ctxt, builderSlot, stockName[i]);
            }
            cob.labelBinding(armEnd);
            nextNameMatch(cob, parser, matcherSlot, ixSlot);
            cob.goto_(loop);
        }

        cob.labelBinding(defaultCase);
        throwIse(cob, "bad property index");

        cob.labelBinding(endObject);
        ldcData(cob, "buildMethod", ConstantDescs.CD_MethodHandle);
        cob.aload(builderSlot);
        cob.invokevirtual(ConstantDescs.CD_MethodHandle, "invokeExact", MTD_BUILD_INVOKE);
        cob.areturn();

        cob.labelBinding(unknown);
        cob.aload(0).aload(parser).aload(ctxt);
        cob.aload(builderSlot);
        cob.invokevirtual(CD_BASE, "_handleUnknown", MTD_HANDLE_UNKNOWN);
        nextNameMatch(cob, parser, matcherSlot, ixSlot);
        cob.goto_(loop);

        cob.labelBinding(oddToken);
        cob.aload(0).aload(parser).aload(ctxt)
           .invokevirtual(CD_BASE, "_unexpectedToken", MTD_DESERIALIZE)
           .areturn();

        emitPropertyHandler(cob, propHandler, ctxt, propSlot, excSlot, builderSlot);
        emitDelegateTail(cob, parser, ctxt, delegate);

        Label scopeEnd = cob.newBoundLabel();
        cob.localVariable(parser, "p", CD_JSON_PARSER, scopeStart, scopeEnd);
        cob.localVariable(ctxt, "ctxt", CD_DESER_CONTEXT, scopeStart, scopeEnd);
        cob.localVariable(builderSlot, "builder", ConstantDescs.CD_Object, scopeStart, scopeEnd);
        cob.localVariable(matcherSlot, "matcher", CD_NAME_MATCHER, scopeStart, scopeEnd);
        cob.localVariable(ixSlot, "ix", ConstantDescs.CD_int, scopeStart, scopeEnd);
        cob.localVariable(propSlot, "prop", CD_SETTABLE_PROP, scopeStart, scopeEnd);
        cob.localVariable(excSlot, "e", CD_EXCEPTION, scopeStart, scopeEnd);
        if (views == ViewStrategy.MASK) {
            cob.localVariable(maskSlot, "viewMask", ConstantDescs.CD_long, scopeStart, scopeEnd);
        }
    }

    // Builder properties on the stock path apply through
    // deserializeSetAndReturn: fluent builders may return a replacement
    // instance, which becomes the new builder local.
    private static void emitStockSetReturn(CodeBuilder cob, int parser, int ctxt, int builderSlot,
            String stockName) {
        ldcData(cob, stockName, CD_SETTABLE_PROP);
        cob.aload(parser).aload(ctxt).aload(builderSlot);
        cob.invokevirtual(CD_SETTABLE_PROP, "deserializeSetAndReturn", MTD_DESER_SET_RETURN);
        cob.astore(builderSlot);
    }

    private static void buildRecordDeserialize(CodeBuilder cob,
            List<GenProp> props, String[] stockName, String[] childName,
            ViewStrategy views, int[] aliasArms) {
        final int parser = 1;
        final int ctxt = 2;

        int next = 3;
        int[] componentSlot = new int[props.size()];
        for (int i = 0; i < props.size(); i++) {
            componentSlot[i] = next;
            Class<?> t = props.get(i).type();
            next += (t == long.class || t == double.class) ? 2 : 1;
        }
        final int matcherSlot = next++;
        final int ixSlot = next++;
        final int seenSlot = next;
        final int propSlot = next + 2;
        final int excSlot = next + 3;
        final int maskSlot = next + 4;
        final int nullMaskSlot = next + 6;
        Label propHandler = cob.newLabel();

        Label scopeStart = cob.newBoundLabel();
        Label delegate = emitEntryGuard(cob, parser, ctxt, views);
        if (views == ViewStrategy.MASK) {
            emitViewMask(cob, ctxt, maskSlot);
        }

        for (int i = 0; i < props.size(); i++) {
            Class<?> t = props.get(i).type();
            if (t == long.class) {
                cob.lconst_0().lstore(componentSlot[i]);
            } else if (t == double.class) {
                cob.dconst_0().dstore(componentSlot[i]);
            } else if (t == float.class) {
                cob.fconst_0().fstore(componentSlot[i]);
            } else if (t.isPrimitive()) {
                cob.iconst_0().istore(componentSlot[i]);
            } else {
                cob.aconst_null().astore(componentSlot[i]);
            }
        }
        cob.lconst_0().lstore(seenSlot);

        ldcData(cob, "matcher", CD_NAME_MATCHER);
        cob.astore(matcherSlot);

        Label loop = cob.newLabel();
        Label switchPart = cob.newLabel();
        Label endObject = cob.newLabel();
        Label unknown = cob.newLabel();
        Label oddToken = cob.newLabel();
        Label defaultCase = cob.newLabel();

        emitFirstMatch(cob, parser, matcherSlot, ixSlot);

        cob.labelBinding(loop);
        cob.iload(ixSlot).ifge(switchPart);
        cob.iload(ixSlot).iconst_m1().if_icmpeq(endObject);
        cob.iload(ixSlot).ldc(-2).if_icmpeq(unknown);
        cob.goto_(oddToken);

        cob.labelBinding(switchPart);
        List<SwitchCase> cases = new ArrayList<>(props.size());
        Label[] caseLabels = new Label[props.size()];
        for (int i = 0; i < props.size(); i++) {
            caseLabels[i] = cob.newLabel();
            cases.add(SwitchCase.of(i, caseLabels[i]));
        }
        // Alias matcher indexes follow the primaries and share their arms.
        int totalNames = props.size() + ((aliasArms == null) ? 0 : aliasArms.length);
        for (int k = props.size(); k < totalNames; k++) {
            cases.add(SwitchCase.of(k, caseLabels[aliasArms[k - props.size()]]));
        }
        cob.iload(ixSlot);
        cob.tableswitch(0, totalNames - 1, defaultCase, cases);

        for (int i = 0; i < props.size(); i++) {
            cob.labelBinding(caseLabels[i]);
            if (views == ViewStrategy.MASK) {
                // A hidden component stays unseen, so required and
                // missing-property reporting treat it exactly like an absent
                // property, matching the stock creator path.
                emitArmViewCheck(cob, parser, ctxt, maskSlot, matcherSlot, ixSlot, i,
                        stockName[i], loop);
            }
            Label armEnd = beginArm(cob, stockName[i], propSlot, propHandler);
            GenProp prop = props.get(i);
            Class<?> t = prop.type();
            switch (prop.kind()) {
                case STRING -> emitRecordScalar(cob, parser, ctxt, componentSlot[i], t,
                        "getString", MTD_GET_STRING, stockName[i], "VALUE_STRING");
                case INT -> emitRecordScalar(cob, parser, ctxt, componentSlot[i], t,
                        "getIntValue", MTD_GET_INT, stockName[i], "VALUE_NUMBER_INT");
                case LONG -> emitRecordScalar(cob, parser, ctxt, componentSlot[i], t,
                        "getLongValue", MTD_GET_LONG, stockName[i], "VALUE_NUMBER_INT");
                case BOOLEAN -> emitRecordScalar(cob, parser, ctxt, componentSlot[i], t,
                        "getBooleanValue", MTD_GET_BOOLEAN, stockName[i], null);
                case CHILD -> {
                    Label childStock = cob.newLabel();
                    Label childDone = cob.newLabel();
                    cob.aload(parser).invokevirtual(CD_JSON_PARSER, "currentToken", MTD_NEXT_TOKEN);
                    cob.getstatic(CD_JSON_TOKEN, "START_OBJECT", CD_JSON_TOKEN);
                    cob.if_acmpne(childStock);
                    emitChildCall(cob, parser, ctxt, childName[i]);
                    storeLocal(cob, t, componentSlot[i]);
                    cob.goto_(childDone);
                    cob.labelBinding(childStock);
                    emitStockValueToLocal(cob, parser, ctxt, componentSlot[i], t, stockName[i]);
                    cob.labelBinding(childDone);
                }
                case STOCK ->
                    emitStockValueToLocal(cob, parser, ctxt, componentSlot[i], t, stockName[i]);
            }
            cob.labelBinding(armEnd);
            cob.lload(seenSlot);
            cob.loadConstant(1L << i);
            cob.lor();
            cob.lstore(seenSlot);
            nextNameMatch(cob, parser, matcherSlot, ixSlot);
            cob.goto_(loop);
        }

        cob.labelBinding(defaultCase);
        throwIse(cob, "bad property index");

        cob.labelBinding(endObject);
        // Missing components: the cold helper mirrors PropertyValueBuffer's
        // required / FAIL_ON_MISSING_CREATOR_PROPERTIES reporting.
        long allSeen = (props.size() == 64) ? -1L : (1L << props.size()) - 1;
        Label allPresent = cob.newLabel();
        cob.lload(seenSlot);
        cob.loadConstant(allSeen);
        cob.lcmp();
        cob.ifeq(allPresent);
        cob.aload(0).aload(ctxt).lload(seenSlot);
        cob.loadConstant(props.size());
        cob.invokevirtual(CD_BASE, "_checkRecordSeen", MTD_CHECK_SEEN);
        cob.labelBinding(allPresent);
        // Reference components that ended null (missing or explicit) feed the
        // cold FAIL_ON_NULL_CREATOR_PROPERTIES check, mirroring
        // PropertyValueBuffer; primitives never do, matching stock defaults.
        cob.lconst_0().lstore(nullMaskSlot);
        for (int i = 0; i < props.size(); i++) {
            if (props.get(i).type().isPrimitive()) {
                continue;
            }
            Label nonNull = cob.newLabel();
            cob.aload(componentSlot[i]);
            cob.ifnonnull(nonNull);
            cob.lload(nullMaskSlot);
            cob.loadConstant(1L << i);
            cob.lor();
            cob.lstore(nullMaskSlot);
            cob.labelBinding(nonNull);
        }
        Label noNulls = cob.newLabel();
        cob.lload(nullMaskSlot);
        cob.lconst_0();
        cob.lcmp();
        cob.ifeq(noNulls);
        cob.aload(0).aload(ctxt).lload(nullMaskSlot);
        cob.loadConstant(props.size());
        cob.invokevirtual(CD_BASE, "_checkRecordNulls", MTD_CHECK_SEEN);
        cob.labelBinding(noNulls);
        // The constructor handle is erased ((e1..en)Object, see MemberHandles),
        // so the call descriptor uses Object for reference components.
        ldcData(cob, "constructor", ConstantDescs.CD_MethodHandle);
        ClassDesc[] paramDescs = new ClassDesc[props.size()];
        for (int i = 0; i < props.size(); i++) {
            Class<?> t = props.get(i).type();
            paramDescs[i] = t.isPrimitive()
                    ? Descs.of(t) : ConstantDescs.CD_Object;
            if (t == long.class) {
                cob.lload(componentSlot[i]);
            } else if (t == double.class) {
                cob.dload(componentSlot[i]);
            } else if (t == float.class) {
                cob.fload(componentSlot[i]);
            } else if (t.isPrimitive()) {
                cob.iload(componentSlot[i]);
            } else {
                cob.aload(componentSlot[i]);
            }
        }
        cob.invokevirtual(ConstantDescs.CD_MethodHandle, "invokeExact",
                MethodTypeDesc.of(ConstantDescs.CD_Object, paramDescs));
        cob.areturn();

        cob.labelBinding(unknown);
        cob.aload(0).aload(parser).aload(ctxt);
        cob.aconst_null();
        cob.invokevirtual(CD_BASE, "_handleUnknown", MTD_HANDLE_UNKNOWN);
        nextNameMatch(cob, parser, matcherSlot, ixSlot);
        cob.goto_(loop);

        cob.labelBinding(oddToken);
        cob.aload(0).aload(parser).aload(ctxt)
           .invokevirtual(CD_BASE, "_unexpectedToken", MTD_DESERIALIZE)
           .areturn();

        emitPropertyHandler(cob, propHandler, ctxt, propSlot, excSlot, -1);
        emitDelegateTail(cob, parser, ctxt, delegate);

        Label scopeEnd = cob.newBoundLabel();
        cob.localVariable(parser, "p", CD_JSON_PARSER, scopeStart, scopeEnd);
        cob.localVariable(ctxt, "ctxt", CD_DESER_CONTEXT, scopeStart, scopeEnd);
        for (int i = 0; i < props.size(); i++) {
            Class<?> t = props.get(i).type();
            cob.localVariable(componentSlot[i], props.get(i).name(),
                    t.isPrimitive() ? Descs.of(t)
                            : ConstantDescs.CD_Object,
                    scopeStart, scopeEnd);
        }
        cob.localVariable(matcherSlot, "matcher", CD_NAME_MATCHER, scopeStart, scopeEnd);
        cob.localVariable(ixSlot, "ix", ConstantDescs.CD_int, scopeStart, scopeEnd);
        cob.localVariable(seenSlot, "seen", ConstantDescs.CD_long, scopeStart, scopeEnd);
        cob.localVariable(propSlot, "prop", CD_SETTABLE_PROP, scopeStart, scopeEnd);
        cob.localVariable(excSlot, "e", CD_EXCEPTION, scopeStart, scopeEnd);
        if (views == ViewStrategy.MASK) {
            cob.localVariable(maskSlot, "viewMask", ConstantDescs.CD_long, scopeStart, scopeEnd);
        }
    }

    private static void emitRecordScalar(CodeBuilder cob, int parser, int ctxt, int slot,
            Class<?> type, String getter, MethodTypeDesc getterType, String stockName,
            String expectedToken) {
        Label useStock = cob.newLabel();
        Label done = cob.newLabel();
        emitExpectedTokenCheck(cob, parser, expectedToken, useStock);
        cob.aload(parser).invokevirtual(CD_JSON_PARSER, getter, getterType);
        storeLocal(cob, type, slot);
        cob.goto_(done);
        cob.labelBinding(useStock);
        emitStockValueToLocal(cob, parser, ctxt, slot, type, stockName);
        cob.labelBinding(done);
    }

    // Reads the whole value through the stock property (parser positioned on
    // the value token). Primitive components unbox; reference components stay
    // Object, since the erased constructor handle casts on invocation.
    private static void emitStockValueToLocal(CodeBuilder cob, int parser, int ctxt, int slot,
            Class<?> type, String stockName) {
        ldcData(cob, stockName, CD_SETTABLE_PROP);
        cob.aload(parser).aload(ctxt);
        cob.invokevirtual(CD_SETTABLE_PROP, "deserialize", MTD_PROP_DESERIALIZE);
        if (type.isPrimitive()) {
            Class<?> box = ClassUtil.wrapperType(type);
            ClassDesc boxDesc = Descs.of(box);
            cob.checkcast(boxDesc);
            cob.invokevirtual(boxDesc, type.getName() + "Value",
                    MethodTypeDesc.of(Descs.of(type)));
        }
        storeLocal(cob, type, slot);
    }

    private static void storeLocal(CodeBuilder cob, Class<?> type, int slot) {
        if (type == long.class) {
            cob.lstore(slot);
        } else if (type == double.class) {
            cob.dstore(slot);
        } else if (type == float.class) {
            cob.fstore(slot);
        } else if (type.isPrimitive()) {
            cob.istore(slot);
        } else {
            cob.astore(slot);
        }
    }

    // The null branch enters deserializeAndSet with the parser already on the
    // VALUE_NULL token, which is the position that method expects. The store
    // is a constant MethodHandle: (Object, eV)void in POJO mode, and
    // (Object, eV)Object in builder mode where the returned builder is kept.
    private static void emitScalar(CodeBuilder cob, int receiverSlot, int parser, int ctxt,
            String getter, MethodTypeDesc getterType, ClassDesc erasedDesc,
            String stockName, String handleName, String expectedToken, boolean builderMode) {
        Label useStock = cob.newLabel();
        Label done = cob.newLabel();
        emitExpectedTokenCheck(cob, parser, expectedToken, useStock);
        ldcData(cob, handleName, ConstantDescs.CD_MethodHandle);
        cob.aload(receiverSlot);
        cob.aload(parser).invokevirtual(CD_JSON_PARSER, getter, getterType);
        emitApplyHandle(cob, receiverSlot, erasedDesc, builderMode);
        cob.goto_(done);
        cob.labelBinding(useStock);
        if (builderMode) {
            emitStockSetReturn(cob, parser, ctxt, receiverSlot, stockName);
        } else {
            emitStockSet(cob, parser, ctxt, receiverSlot, stockName);
        }
        cob.labelBinding(done);
    }

    private static void emitApplyHandle(CodeBuilder cob, int receiverSlot, ClassDesc erasedDesc,
            boolean builderMode) {
        if (builderMode) {
            cob.invokevirtual(ConstantDescs.CD_MethodHandle, "invokeExact", MethodTypeDesc.of(
                    ConstantDescs.CD_Object, ConstantDescs.CD_Object, erasedDesc));
            cob.astore(receiverSlot);
        } else {
            cob.invokevirtual(ConstantDescs.CD_MethodHandle, "invokeExact", MethodTypeDesc.of(
                    ConstantDescs.CD_void, ConstantDescs.CD_Object, erasedDesc));
        }
    }

    private static void emitChildArm(CodeBuilder cob, int receiverSlot, int parser, int ctxt,
            String childName, String stockName, String handleName, boolean builderMode) {
        Label childStock = cob.newLabel();
        Label childDone = cob.newLabel();
        // The fused match left the value token current.
        cob.aload(parser).invokevirtual(CD_JSON_PARSER, "currentToken", MTD_NEXT_TOKEN);
        cob.getstatic(CD_JSON_TOKEN, "START_OBJECT", CD_JSON_TOKEN);
        cob.if_acmpne(childStock);
        ldcData(cob, handleName, ConstantDescs.CD_MethodHandle);
        cob.aload(receiverSlot);
        emitChildCall(cob, parser, ctxt, childName);
        emitApplyHandle(cob, receiverSlot, ConstantDescs.CD_Object, builderMode);
        cob.goto_(childDone);
        cob.labelBinding(childStock);
        if (builderMode) {
            emitStockSetReturn(cob, parser, ctxt, receiverSlot, stockName);
        } else {
            emitStockSet(cob, parser, ctxt, receiverSlot, stockName);
        }
        cob.labelBinding(childDone);
    }

    private static void emitChildCall(CodeBuilder cob, int parser, int ctxt, String childName) {
        ldcData(cob, childName, CD_BASE);
        cob.aload(parser).aload(ctxt);
        cob.invokevirtual(CD_BASE, "deserialize", MTD_DESERIALIZE);
    }

    private static void emitStockSet(CodeBuilder cob, int parser, int ctxt, int beanSlot,
            String stockName) {
        ldcData(cob, stockName, CD_SETTABLE_PROP);
        cob.aload(parser).aload(ctxt).aload(beanSlot);
        cob.invokevirtual(CD_SETTABLE_PROP, "deserializeAndSet", MTD_DESERIALIZE_AND_SET);
    }

    // Guards the generated loop's entry: anything the loop does not model - a
    // stream positioned on neither START_OBJECT nor PROPERTY_NAME (the
    // AsProperty polymorphic path hands subtype deserializers a stream on the
    // property after the type id) and, under the DELEGATE strategy only, an
    // active view - branches to the returned label, whose stock-delegation
    // tail the caller emits at the end of the method so the main body
    // decompiles un-nested. The MASK strategy keeps view-active calls on the
    // generated path through the visibility bitmask.
    private static Label emitEntryGuard(CodeBuilder cob, int parser, int ctxt,
            ViewStrategy views) {
        Label delegate = cob.newLabel();
        Label entryOk = cob.newLabel();
        cob.aload(parser).invokevirtual(CD_JSON_PARSER, "currentToken", MTD_NEXT_TOKEN);
        cob.getstatic(CD_JSON_TOKEN, "START_OBJECT", CD_JSON_TOKEN);
        cob.if_acmpeq(entryOk);
        cob.aload(parser).invokevirtual(CD_JSON_PARSER, "currentToken", MTD_NEXT_TOKEN);
        cob.getstatic(CD_JSON_TOKEN, "PROPERTY_NAME", CD_JSON_TOKEN);
        cob.if_acmpne(delegate);
        cob.labelBinding(entryOk);
        if (views == ViewStrategy.DELEGATE) {
            cob.aload(ctxt).invokevirtual(CD_DESER_CONTEXT, "getActiveView",
                    MTD_GET_ACTIVE_VIEW);
            cob.ifnonnull(delegate);
        }
        return delegate;
    }

    private static void emitDelegateTail(CodeBuilder cob, int parser, int ctxt, Label delegate) {
        cob.labelBinding(delegate);
        cob.aload(0).getfield(CD_BASE, "_fallback", CD_BEAN_DESER_BASE);
        cob.aload(parser).aload(ctxt);
        cob.invokevirtual(CD_BEAN_DESER_BASE, "deserialize", MTD_DESERIALIZE);
        cob.areturn();
    }

    // Advances to the value token and branches to useStock unless it is the
    // token the inline read expects. Null, quoted scalars, and mismatched
    // shapes all take the stock property, which owns coercion and null
    // handling. expectedToken null selects the boolean pair.
    private static void emitExpectedTokenCheck(CodeBuilder cob, int parser,
            String expectedToken, Label useStock) {
        // The fused match already advanced to the value token, so read it
        // with currentToken rather than advancing again.
        cob.aload(parser).invokevirtual(CD_JSON_PARSER, "currentToken", MTD_NEXT_TOKEN);
        if (expectedToken != null) {
            cob.getstatic(CD_JSON_TOKEN, expectedToken, CD_JSON_TOKEN);
            cob.if_acmpne(useStock);
        } else {
            Label isTrue = cob.newLabel();
            Label fast = cob.newLabel();
            cob.dup();
            cob.getstatic(CD_JSON_TOKEN, "VALUE_TRUE", CD_JSON_TOKEN);
            cob.if_acmpeq(isTrue);
            cob.getstatic(CD_JSON_TOKEN, "VALUE_FALSE", CD_JSON_TOKEN);
            cob.if_acmpne(useStock);
            cob.goto_(fast);
            cob.labelBinding(isTrue);
            cob.pop();
            cob.labelBinding(fast);
        }
    }

    // Loads the arm's stock property into propSlot and opens its exception
    // region: any Exception from a property arm is rethrown with the property
    // reference prepended, like the stock loop's wrapAndThrow.
    private static Label beginArm(CodeBuilder cob, String stockName, int propSlot, Label handler) {
        ldcData(cob, stockName, CD_SETTABLE_PROP);
        cob.astore(propSlot);
        Label armStart = cob.newLabel();
        Label armEnd = cob.newLabel();
        cob.exceptionCatch(armStart, armEnd, handler, CD_EXCEPTION);
        cob.labelBinding(armStart);
        return armEnd;
    }

    // receiverSlot < 0 selects aconst_null (record mode: no instance yet).
    private static void emitPropertyHandler(CodeBuilder cob, Label handler, int ctxt,
            int propSlot, int excSlot, int receiverSlot) {
        cob.labelBinding(handler);
        cob.astore(excSlot);
        cob.aload(0);
        cob.aload(excSlot);
        if (receiverSlot < 0) {
            cob.aconst_null();
        } else {
            cob.aload(receiverSlot);
        }
        cob.aload(propSlot);
        cob.aload(ctxt);
        cob.invokevirtual(CD_BASE, "_propertyException", MTD_PROP_WRAP);
        cob.athrow();
    }

    // The fused name match: on a non-negative result the current token is the
    // property's value token, so the arms consume it directly; negative
    // results leave the stream on the name exactly as nextNameMatch does.
    private static void nextNameMatch(CodeBuilder cob, int parser, int matcherSlot, int ixSlot) {
        cob.aload(parser).aload(matcherSlot)
                .invokevirtual(CD_JSON_PARSER, "nextNameMatchAndToken", MTD_NEXT_NAME_MATCH)
                .istore(ixSlot);
    }

    // First match of the loop. The entry guard admits START_OBJECT and
    // PROPERTY_NAME; a name entry matches the CURRENT name, mirroring stock
    // BeanDeserializer's currentNameMatch loop head. The fused arms consume
    // the current token, so a matched name entry advances to its value here;
    // fusing the entry itself would double-advance (the current name is
    // already consumed). Negative results stay on the name, as the unknown
    // arm expects.
    private static void emitFirstMatch(CodeBuilder cob, int parser, int matcherSlot, int ixSlot) {
        Label nameEntry = cob.newLabel();
        Label done = cob.newLabel();
        cob.aload(parser).invokevirtual(CD_JSON_PARSER, "currentToken", MTD_NEXT_TOKEN);
        cob.getstatic(CD_JSON_TOKEN, "PROPERTY_NAME", CD_JSON_TOKEN);
        cob.if_acmpeq(nameEntry);
        nextNameMatch(cob, parser, matcherSlot, ixSlot);
        cob.goto_(done);
        cob.labelBinding(nameEntry);
        cob.aload(parser).aload(matcherSlot)
                .invokevirtual(CD_JSON_PARSER, "currentNameMatch", MTD_NEXT_NAME_MATCH)
                .istore(ixSlot);
        cob.iload(ixSlot).iflt(done);
        cob.aload(parser).invokevirtual(CD_JSON_PARSER, "nextToken", MTD_NEXT_TOKEN).pop();
        cob.labelBinding(done);
    }

    private static void throwIse(CodeBuilder cob, String message) {
        cob.new_(CD_ISE).dup().ldc(message)
                .invokespecial(CD_ISE, ConstantDescs.INIT_NAME,
                        MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_String))
                .athrow();
    }
}
