package tools.jackson.module.blackbird.codegen;

import java.lang.classfile.ClassFile;
import java.lang.classfile.CodeBuilder;
import java.lang.classfile.Label;
import java.lang.classfile.attribute.MethodParametersAttribute;
import java.lang.constant.ClassDesc;
import java.lang.constant.ConstantDescs;
import java.lang.constant.DynamicConstantDesc;
import java.lang.constant.MethodTypeDesc;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import tools.jackson.core.JsonGenerator;
import tools.jackson.core.JsonToken;
import tools.jackson.core.SerializableString;
import tools.jackson.core.type.WritableTypeId;
import tools.jackson.databind.SerializationContext;
import tools.jackson.databind.ValueSerializer;
import tools.jackson.databind.jsontype.TypeSerializer;
import tools.jackson.databind.ser.PropertyWriter;
import tools.jackson.databind.ser.bean.BeanSerializerBase;
import tools.jackson.module.blackbird.codegen.BeanReaderGenerator.ViewStrategy;
import tools.jackson.module.blackbird.internal.GeneratedWriterBase;

/**
 * Emits a hidden-class serializer for one bean: a straight-line sequence of
 * writeName/write-value pairs with pre-encoded name constants for eligible
 * properties and the stock PropertyWriter (a named classData constant) for
 * everything else. Property values load through constant (Object)eV
 * MethodHandles (see {@link MemberHandles}), so the generated bytecode never
 * names the bean class and every codec defines in the module's own context.
 * Beans that declare views resolve a per-view visibility bitmask and each
 * property tests its bit, so view-active writes stay on the generated path;
 * beans with more than 64 properties delegate view-active calls to the stock
 * serializer instead.
 */
public final class BeanWriterGenerator
{
    public enum WKind { STRING, INT, LONG, BOOLEAN, CHILD, STOCK }

    // handle loads the property value from the bean, erased to (Object)eV
    // (a getter call or a field read); null for STOCK.
    public record GenWProp(WKind kind, PropertyWriter stock,
            SerializableString name, GeneratedWriterBase child, MethodHandle handle) {}

    private static final ClassDesc CD_JSON_GENERATOR = Descs.of(JsonGenerator.class);
    private static final ClassDesc CD_SER_CONTEXT = Descs.of(SerializationContext.class);
    private static final ClassDesc CD_SERIALIZABLE_STRING = Descs.of(SerializableString.class);
    private static final ClassDesc CD_PROPERTY_WRITER = Descs.of(PropertyWriter.class);
    private static final ClassDesc CD_WRITER_BASE =
            Descs.of(GeneratedWriterBase.class);
    private static final ClassDesc CD_BEAN_SER_BASE = Descs.of(BeanSerializerBase.class);

    private static final MethodTypeDesc MTD_SERIALIZE = MethodTypeDesc.of(ConstantDescs.CD_void,
            ConstantDescs.CD_Object, CD_JSON_GENERATOR, CD_SER_CONTEXT);
    private static final MethodTypeDesc MTD_WRITE_NAME =
            MethodTypeDesc.of(CD_JSON_GENERATOR, CD_SERIALIZABLE_STRING);
    private static final MethodTypeDesc MTD_WRITE_STRING =
            MethodTypeDesc.of(CD_JSON_GENERATOR, ConstantDescs.CD_String);
    private static final MethodTypeDesc MTD_WRITE_INT =
            MethodTypeDesc.of(CD_JSON_GENERATOR, ConstantDescs.CD_int);
    private static final MethodTypeDesc MTD_WRITE_LONG =
            MethodTypeDesc.of(CD_JSON_GENERATOR, ConstantDescs.CD_long);
    private static final MethodTypeDesc MTD_WRITE_BOOLEAN =
            MethodTypeDesc.of(CD_JSON_GENERATOR, ConstantDescs.CD_boolean);
    private static final MethodTypeDesc MTD_WRITE_NULL = MethodTypeDesc.of(CD_JSON_GENERATOR);
    private static final MethodTypeDesc MTD_WRITE_START_OBJECT =
            MethodTypeDesc.of(CD_JSON_GENERATOR, ConstantDescs.CD_Object);
    private static final MethodTypeDesc MTD_WRITE_END = MethodTypeDesc.of(CD_JSON_GENERATOR);
    private static final MethodTypeDesc MTD_SERIALIZE_AS_PROPERTY = MethodTypeDesc.of(
            ConstantDescs.CD_void, ConstantDescs.CD_Object, CD_JSON_GENERATOR, CD_SER_CONTEXT);
    private static final MethodTypeDesc MTD_CTOR =
            MethodTypeDesc.of(ConstantDescs.CD_void, CD_BEAN_SER_BASE);
    private static final MethodTypeDesc MTD_GET_ACTIVE_VIEW =
            MethodTypeDesc.of(ConstantDescs.CD_Class);
    private static final MethodTypeDesc MTD_VIEW_MASK =
            MethodTypeDesc.of(ConstantDescs.CD_long, ConstantDescs.CD_Class);
    private static final MethodTypeDesc MTD_PROP_VISIBLE = MethodTypeDesc.of(
            ConstantDescs.CD_boolean, CD_PROPERTY_WRITER, ConstantDescs.CD_Class,
            ConstantDescs.CD_boolean);
    private static final ClassDesc CD_JSON_TOKEN = Descs.of(JsonToken.class);
    private static final ClassDesc CD_TYPE_SERIALIZER =
            Descs.of(TypeSerializer.class);
    private static final ClassDesc CD_WRITABLE_TYPE_ID =
            Descs.of(WritableTypeId.class);
    private static final MethodTypeDesc MTD_TYPE_ID = MethodTypeDesc.of(
            CD_WRITABLE_TYPE_ID, ConstantDescs.CD_Object, CD_JSON_TOKEN);
    private static final MethodTypeDesc MTD_WRITE_TYPE_PART = MethodTypeDesc.of(
            CD_WRITABLE_TYPE_ID, CD_JSON_GENERATOR, CD_SER_CONTEXT, CD_WRITABLE_TYPE_ID);
    private static final MethodTypeDesc MTD_ASSIGN_CURRENT =
            MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_Object);
    private static final MethodTypeDesc MTD_SERIALIZE_WITH_TYPE = MethodTypeDesc.of(
            ConstantDescs.CD_void, ConstantDescs.CD_Object, CD_JSON_GENERATOR, CD_SER_CONTEXT,
            CD_TYPE_SERIALIZER);

    // Named class-data entries through the writer base's classDataEntry
    // bootstrap; rationale in BeanReaderGenerator.
    private static final java.lang.constant.DirectMethodHandleDesc BSM_DATA_ENTRY =
            ConstantDescs.ofConstantBootstrap(CD_WRITER_BASE, "classDataEntry",
                    ConstantDescs.CD_Object);

    private BeanWriterGenerator() {}

    private static void ldcData(CodeBuilder cob, String name, ClassDesc type) {
        cob.ldc(DynamicConstantDesc.ofNamed(BSM_DATA_ENTRY, name, type));
    }

    // nativePolyWrites: emit a serializeWithType override matching stock
    // BeanSerializerBase's WritableTypeId flow; false (a @JsonTypeId property
    // exists, whose value feeds the type id) keeps the base forwarding.
    @SuppressWarnings("unchecked")
    public static ValueSerializer<Object> generate(Class<?> beanClass, List<GenWProp> props,
            BeanSerializerBase fallback, ViewStrategy views, boolean includeByDefault,
            boolean nativePolyWrites)
            throws ReflectiveOperationException {
        Map<String, Object> classData = new LinkedHashMap<>();
        String[] stockName = new String[props.size()];
        String[] nameName = new String[props.size()];
        String[] childName = new String[props.size()];
        String[] handleName = new String[props.size()];
        for (int i = 0; i < props.size(); i++) {
            GenWProp p = props.get(i);
            String base = p.stock().getName();
            stockName[i] = BeanReaderGenerator.dataName(classData, base + "Writer");
            classData.put(stockName[i], p.stock());
            if (p.name() != null) {
                nameName[i] = BeanReaderGenerator.dataName(classData, base + "Name");
                classData.put(nameName[i], p.name());
            }
            if (p.child() != null) {
                childName[i] = BeanReaderGenerator.dataName(classData, base + "Codec");
                classData.put(childName[i], p.child());
            }
            if (p.handle() != null) {
                handleName[i] = BeanReaderGenerator.dataName(classData, base + "Get");
                classData.put(handleName[i], p.handle());
            }
        }

        MethodHandles.Lookup definer = MethodHandles.lookup();
        byte[] bytes = buildClass(definer.lookupClass().getPackageName(), beanClass, props,
                stockName, nameName, childName, handleName, views, includeByDefault,
                nativePolyWrites);
        CodegenDump.dump(beanClass, "writer", bytes);
        // Module-context defines never legitimately fail: any throw here is a
        // generator bug, surfaced through the modifier's failure handling.
        MethodHandles.Lookup hidden = definer.defineHiddenClassWithClassData(
                bytes, Map.copyOf(classData), true);
        MethodHandle ctor = hidden.findConstructor(hidden.lookupClass(),
                MethodType.methodType(void.class, BeanSerializerBase.class));
        try {
            return (ValueSerializer<Object>) ctor.invoke(fallback);
        } catch (Throwable t) {
            throw new IllegalStateException("cannot instantiate generated writer", t);
        }
    }

    // C2 refuses to inline a hot method whose bytecode exceeds FreqInlineSize
    // (default 325). The scalar helpers are padded past that limit so each
    // compiles standalone: on aarch64, inlined copies of writeName and the
    // NumberOutput digit paths inside a large generated body run 2-3x slower
    // than their standalone compilations, which costs number-heavy shapes ~24%.
    // Out-of-line helper calls measure at parity with the best inlined layout.
    private static final int INLINE_PAD = 384;

    private static final MethodTypeDesc MTD_HELP_STRING = MethodTypeDesc.of(ConstantDescs.CD_void,
            CD_JSON_GENERATOR, CD_SERIALIZABLE_STRING, ConstantDescs.CD_String);
    private static final MethodTypeDesc MTD_HELP_INT = MethodTypeDesc.of(ConstantDescs.CD_void,
            CD_JSON_GENERATOR, CD_SERIALIZABLE_STRING, ConstantDescs.CD_int);
    private static final MethodTypeDesc MTD_HELP_LONG = MethodTypeDesc.of(ConstantDescs.CD_void,
            CD_JSON_GENERATOR, CD_SERIALIZABLE_STRING, ConstantDescs.CD_long);
    private static final MethodTypeDesc MTD_HELP_BOOLEAN = MethodTypeDesc.of(ConstantDescs.CD_void,
            CD_JSON_GENERATOR, CD_SERIALIZABLE_STRING, ConstantDescs.CD_boolean);
    private static final MethodTypeDesc MTD_HELP_NAME = MethodTypeDesc.of(ConstantDescs.CD_void,
            CD_JSON_GENERATOR, CD_SERIALIZABLE_STRING);

    private static byte[] buildClass(String targetPackage, Class<?> beanClass,
            List<GenWProp> props,
            String[] stockName, String[] nameName, String[] childName, String[] handleName,
            ViewStrategy views, boolean includeByDefault, boolean nativePolyWrites) {
        // A hidden class must be named in its define context's package.
        ClassDesc thisClass = ClassDesc.of(
                targetPackage + ".BBWriter_" + BeanReaderGenerator.codecName(beanClass));
        return ClassFile.of().build(thisClass, clb -> {
            clb.withFlags(ClassFile.ACC_PUBLIC | ClassFile.ACC_FINAL | ClassFile.ACC_SUPER);
            clb.withSuperclass(CD_WRITER_BASE);
            clb.withMethod(ConstantDescs.INIT_NAME, MTD_CTOR, ClassFile.ACC_PUBLIC,
                    mb -> mb.with(BeanReaderGenerator.params("fallback"))
                            .withCode(cob -> cob.aload(0).aload(1)
                                    .invokespecial(CD_WRITER_BASE, ConstantDescs.INIT_NAME, MTD_CTOR)
                                    .return_()));
            clb.withMethod("serialize", MTD_SERIALIZE, ClassFile.ACC_PUBLIC,
                    mb -> mb.with(BeanReaderGenerator.params("value", "g", "ctxt"))
                            .withCode(cob -> buildSerialize(cob, thisClass, props,
                                    stockName, nameName, childName, handleName, views)));
            if (nativePolyWrites) {
                clb.withMethod("serializeWithType", MTD_SERIALIZE_WITH_TYPE, ClassFile.ACC_PUBLIC,
                        mb -> mb.with(BeanReaderGenerator.params("value", "g", "ctxt", "typeSer"))
                                .withCode(cob -> buildSerializeWithType(cob, thisClass, props,
                                        stockName, nameName, childName, handleName, views)));
            }
            emitHelpers(clb, thisClass, props);
            if (views == ViewStrategy.MASK) {
                emitComputeViewMask(clb, props, stockName, includeByDefault);
            }
        });
    }

    private static void emitHelpers(java.lang.classfile.ClassBuilder clb, ClassDesc thisClass,
            List<GenWProp> props) {
        boolean needName = false;
        boolean[] kinds = new boolean[WKind.values().length];
        for (GenWProp p : props) {
            kinds[p.kind().ordinal()] = true;
            if (p.kind() == WKind.CHILD) {
                needName = true;
            }
        }
        if (kinds[WKind.STRING.ordinal()]) {
            emitPadded(clb, "$str", MTD_HELP_STRING, cob -> {
                cob.aload(0).aload(1)
                   .invokevirtual(CD_JSON_GENERATOR, "writeName", MTD_WRITE_NAME).pop();
                Label isNull = cob.newLabel();
                Label done = cob.newLabel();
                cob.aload(2).ifnull(isNull);
                cob.aload(0).aload(2)
                   .invokevirtual(CD_JSON_GENERATOR, "writeString", MTD_WRITE_STRING).pop();
                cob.goto_(done);
                cob.labelBinding(isNull);
                cob.aload(0).invokevirtual(CD_JSON_GENERATOR, "writeNull", MTD_WRITE_NULL).pop();
                cob.labelBinding(done);
                cob.return_();
            });
        }
        if (kinds[WKind.INT.ordinal()]) {
            emitPadded(clb, "$int", MTD_HELP_INT, cob -> cob.aload(0).aload(1)
                    .invokevirtual(CD_JSON_GENERATOR, "writeName", MTD_WRITE_NAME).pop()
                    .aload(0).iload(2)
                    .invokevirtual(CD_JSON_GENERATOR, "writeNumber", MTD_WRITE_INT).pop()
                    .return_());
        }
        if (kinds[WKind.LONG.ordinal()]) {
            emitPadded(clb, "$long", MTD_HELP_LONG, cob -> cob.aload(0).aload(1)
                    .invokevirtual(CD_JSON_GENERATOR, "writeName", MTD_WRITE_NAME).pop()
                    .aload(0).lload(2)
                    .invokevirtual(CD_JSON_GENERATOR, "writeNumber", MTD_WRITE_LONG).pop()
                    .return_());
        }
        if (kinds[WKind.BOOLEAN.ordinal()]) {
            emitPadded(clb, "$bool", MTD_HELP_BOOLEAN, cob -> cob.aload(0).aload(1)
                    .invokevirtual(CD_JSON_GENERATOR, "writeName", MTD_WRITE_NAME).pop()
                    .aload(0).iload(2)
                    .invokevirtual(CD_JSON_GENERATOR, "writeBoolean", MTD_WRITE_BOOLEAN).pop()
                    .return_());
        }
        if (needName) {
            emitPadded(clb, "$name", MTD_HELP_NAME, cob -> cob.aload(0).aload(1)
                    .invokevirtual(CD_JSON_GENERATOR, "writeName", MTD_WRITE_NAME).pop()
                    .return_());
        }
    }

    private static void emitPadded(java.lang.classfile.ClassBuilder clb, String name,
            MethodTypeDesc type, java.util.function.Consumer<CodeBuilder> body) {
        MethodParametersAttribute helperParams = (type.parameterCount() == 2)
                ? BeanReaderGenerator.params("g", "name")
                : BeanReaderGenerator.params("g", "name", "value");
        clb.withMethod(name, type, ClassFile.ACC_PRIVATE | ClassFile.ACC_STATIC,
                mb -> mb.with(helperParams).withCode(cob -> {
            for (int i = 0; i < INLINE_PAD; i++) {
                cob.nop();
            }
            body.accept(cob);
        }));
    }

    private static void buildSerialize(CodeBuilder cob, ClassDesc thisClass,
            List<GenWProp> props, String[] stockName, String[] nameName, String[] childName,
            String[] handleName, ViewStrategy views) {
        final int gen = 2;
        final int ctxt = 3;
        final int refSlot = 5;
        final int maskSlot = 6;

        Label scopeStart = cob.newBoundLabel();
        Label delegate = null;
        if (views == ViewStrategy.DELEGATE) {
            // View-active calls (declared views with more than 64 properties,
            // or the write-nothing inclusion-off case) go to the stock
            // serializer, whose tail sits after the body so the main path
            // decompiles un-nested.
            delegate = cob.newLabel();
            cob.aload(ctxt).invokevirtual(CD_SER_CONTEXT, "getActiveView", MTD_GET_ACTIVE_VIEW);
            cob.ifnonnull(delegate);
        } else if (views == ViewStrategy.MASK) {
            emitViewMask(cob, ctxt, maskSlot);
        }

        cob.aload(gen).aload(1)
           .invokevirtual(CD_JSON_GENERATOR, "writeStartObject", MTD_WRITE_START_OBJECT).pop();

        emitProps(cob, thisClass, props, stockName, nameName, childName, handleName, views,
                gen, ctxt, refSlot, maskSlot);

        cob.aload(gen).invokevirtual(CD_JSON_GENERATOR, "writeEndObject", MTD_WRITE_END).pop();
        cob.return_();
        if (delegate != null) {
            cob.labelBinding(delegate);
            cob.aload(0).getfield(CD_WRITER_BASE, "_fallback", CD_BEAN_SER_BASE);
            cob.aload(1).aload(gen).aload(ctxt);
            cob.invokevirtual(CD_BEAN_SER_BASE, "serialize", MTD_SERIALIZE);
            cob.return_();
        }

        Label scopeEnd = cob.newBoundLabel();
        cob.localVariable(1, "value", ConstantDescs.CD_Object, scopeStart, scopeEnd);
        cob.localVariable(gen, "g", CD_JSON_GENERATOR, scopeStart, scopeEnd);
        cob.localVariable(ctxt, "ctxt", CD_SER_CONTEXT, scopeStart, scopeEnd);
        // Slot entries must stay within max_locals, so name the child slot
        // only when some CHILD arm actually stores it.
        if (props.stream().anyMatch(pr -> pr.kind() == WKind.CHILD)) {
            cob.localVariable(refSlot, "child", ConstantDescs.CD_Object, scopeStart, scopeEnd);
        }
        if (views == ViewStrategy.MASK) {
            cob.localVariable(maskSlot, "viewMask", ConstantDescs.CD_long, scopeStart, scopeEnd);
        }
    }

    // The serializeWithType override: stock BeanSerializerBase's flow with
    // the object-id and filter-id branches omitted (both gate at the factory)
    // and the type id always typeSer.typeId(value, START_OBJECT) - beans with
    // a @JsonTypeId property keep the base forwarding instead. The props body
    // is emitted again rather than shared through a method so the plain
    // serialize path keeps its measured shape.
    private static void buildSerializeWithType(CodeBuilder cob, ClassDesc thisClass,
            List<GenWProp> props, String[] stockName, String[] nameName, String[] childName,
            String[] handleName, ViewStrategy views) {
        final int gen = 2;
        final int ctxt = 3;
        final int typeSer = 4;
        final int typeIdSlot = 5;
        final int refSlot = 6;
        final int maskSlot = 7;

        Label scopeStart = cob.newBoundLabel();
        Label delegate = null;
        if (views == ViewStrategy.DELEGATE) {
            delegate = cob.newLabel();
            cob.aload(ctxt).invokevirtual(CD_SER_CONTEXT, "getActiveView", MTD_GET_ACTIVE_VIEW);
            cob.ifnonnull(delegate);
        } else if (views == ViewStrategy.MASK) {
            emitViewMask(cob, ctxt, maskSlot);
        }

        cob.aload(typeSer).aload(1);
        cob.getstatic(CD_JSON_TOKEN, "START_OBJECT", CD_JSON_TOKEN);
        cob.invokevirtual(CD_TYPE_SERIALIZER, "typeId", MTD_TYPE_ID);
        cob.astore(typeIdSlot);
        cob.aload(typeSer).aload(gen).aload(ctxt).aload(typeIdSlot);
        cob.invokevirtual(CD_TYPE_SERIALIZER, "writeTypePrefix", MTD_WRITE_TYPE_PART).pop();
        cob.aload(gen).aload(1)
           .invokevirtual(CD_JSON_GENERATOR, "assignCurrentValue", MTD_ASSIGN_CURRENT);

        emitProps(cob, thisClass, props, stockName, nameName, childName, handleName, views,
                gen, ctxt, refSlot, maskSlot);

        cob.aload(typeSer).aload(gen).aload(ctxt).aload(typeIdSlot);
        cob.invokevirtual(CD_TYPE_SERIALIZER, "writeTypeSuffix", MTD_WRITE_TYPE_PART).pop();
        cob.return_();
        if (delegate != null) {
            cob.labelBinding(delegate);
            cob.aload(0).getfield(CD_WRITER_BASE, "_fallback", CD_BEAN_SER_BASE);
            cob.aload(1).aload(gen).aload(ctxt).aload(typeSer);
            cob.invokevirtual(CD_BEAN_SER_BASE, "serializeWithType", MTD_SERIALIZE_WITH_TYPE);
            cob.return_();
        }

        Label scopeEnd = cob.newBoundLabel();
        cob.localVariable(1, "value", ConstantDescs.CD_Object, scopeStart, scopeEnd);
        cob.localVariable(gen, "g", CD_JSON_GENERATOR, scopeStart, scopeEnd);
        cob.localVariable(ctxt, "ctxt", CD_SER_CONTEXT, scopeStart, scopeEnd);
        cob.localVariable(typeSer, "typeSer", CD_TYPE_SERIALIZER, scopeStart, scopeEnd);
        cob.localVariable(typeIdSlot, "typeIdDef", CD_WRITABLE_TYPE_ID, scopeStart, scopeEnd);
        if (props.stream().anyMatch(pr -> pr.kind() == WKind.CHILD)) {
            cob.localVariable(refSlot, "child", ConstantDescs.CD_Object, scopeStart, scopeEnd);
        }
        if (views == ViewStrategy.MASK) {
            cob.localVariable(maskSlot, "viewMask", ConstantDescs.CD_long, scopeStart, scopeEnd);
        }
    }

    // MASK strategy: resolves the visibility bitmask for the call (all-ones
    // when no view is active) into maskSlot.
    private static void emitViewMask(CodeBuilder cob, int ctxt, int maskSlot) {
        Label nullView = cob.newLabel();
        Label haveMask = cob.newLabel();
        cob.aload(ctxt).invokevirtual(CD_SER_CONTEXT, "getActiveView", MTD_GET_ACTIVE_VIEW);
        cob.dup();
        cob.ifnull(nullView);
        cob.aload(0);
        cob.swap();
        cob.invokevirtual(CD_WRITER_BASE, "_viewMask", MTD_VIEW_MASK);
        cob.lstore(maskSlot);
        cob.goto_(haveMask);
        cob.labelBinding(nullView);
        cob.pop();
        cob.loadConstant(-1L);
        cob.lstore(maskSlot);
        cob.labelBinding(haveMask);
    }

    // One writeName/write-value pair per property, the bean in slot 1.
    private static void emitProps(CodeBuilder cob, ClassDesc thisClass, List<GenWProp> props,
            String[] stockName, String[] nameName, String[] childName, String[] handleName,
            ViewStrategy views, int gen, int ctxt, int refSlot, int maskSlot) {
        for (int i = 0; i < props.size(); i++) {
            GenWProp prop = props.get(i);
            Label hidden = null;
            if (views == ViewStrategy.MASK) {
                hidden = cob.newLabel();
                cob.lload(maskSlot);
                cob.loadConstant(1L << i);
                cob.land();
                cob.lconst_0();
                cob.lcmp();
                cob.ifeq(hidden);
            }
            switch (prop.kind()) {
                case INT -> emitScalar(cob, thisClass, gen, nameName[i], handleName[i],
                        "$int", MTD_HELP_INT, ConstantDescs.CD_int);
                case LONG -> emitScalar(cob, thisClass, gen, nameName[i], handleName[i],
                        "$long", MTD_HELP_LONG, ConstantDescs.CD_long);
                case BOOLEAN -> emitScalar(cob, thisClass, gen, nameName[i], handleName[i],
                        "$bool", MTD_HELP_BOOLEAN, ConstantDescs.CD_boolean);
                case STRING -> {
                    // The getter handle is erased to (Object)Object; the value
                    // is a String at run time (java.lang, not a bean name), so
                    // a checkcast recovers the helper's descriptor.
                    cob.aload(gen);
                    ldcData(cob, nameName[i], CD_SERIALIZABLE_STRING);
                    emitLoad(cob, handleName[i], ConstantDescs.CD_Object);
                    cob.checkcast(ConstantDescs.CD_String);
                    cob.invokestatic(thisClass, "$str", MTD_HELP_STRING);
                }
                case CHILD -> {
                    cob.aload(gen);
                    ldcData(cob, nameName[i], CD_SERIALIZABLE_STRING);
                    cob.invokestatic(thisClass, "$name", MTD_HELP_NAME);
                    emitLoad(cob, handleName[i], ConstantDescs.CD_Object);
                    cob.astore(refSlot);
                    final String childEntry = childName[i];
                    emitNullableRef(cob, gen, refSlot, () -> {
                        ldcData(cob, childEntry, CD_WRITER_BASE);
                        cob.aload(refSlot).aload(gen).aload(ctxt);
                        cob.invokevirtual(CD_WRITER_BASE, "serialize", MTD_SERIALIZE);
                    });
                }
                case STOCK -> {
                    ldcData(cob, stockName[i], CD_PROPERTY_WRITER);
                    cob.aload(1).aload(gen).aload(ctxt);
                    cob.invokevirtual(CD_PROPERTY_WRITER, "serializeAsProperty",
                            MTD_SERIALIZE_AS_PROPERTY);
                }
            }
            if (hidden != null) {
                cob.labelBinding(hidden);
            }
        }
    }

    // Overrides GeneratedWriterBase._computeViewMask: bit i set when property
    // i is visible in the view, per the same rule the stock factory uses to
    // build the filtered writer array.
    private static void emitComputeViewMask(java.lang.classfile.ClassBuilder clb,
            List<GenWProp> props, String[] stockName, boolean includeByDefault) {
        clb.withMethod("_computeViewMask", MTD_VIEW_MASK, ClassFile.ACC_PROTECTED,
                mb -> mb.with(BeanReaderGenerator.params("activeView")).withCode(cob -> {
            final int maskSlot = 2;
            Label scopeStart = cob.newBoundLabel();
            cob.lconst_0().lstore(maskSlot);
            for (int i = 0; i < props.size(); i++) {
                Label skip = cob.newLabel();
                ldcData(cob, stockName[i], CD_PROPERTY_WRITER);
                cob.aload(1);
                cob.loadConstant(includeByDefault ? 1 : 0);
                cob.invokestatic(CD_WRITER_BASE, "_propVisible", MTD_PROP_VISIBLE);
                cob.ifeq(skip);
                cob.lload(maskSlot);
                cob.loadConstant(1L << i);
                cob.lor();
                cob.lstore(maskSlot);
                cob.labelBinding(skip);
            }
            cob.lload(maskSlot).lreturn();
            Label scopeEnd = cob.newBoundLabel();
            cob.localVariable(1, "activeView", ConstantDescs.CD_Class, scopeStart, scopeEnd);
            cob.localVariable(maskSlot, "mask", ConstantDescs.CD_long, scopeStart, scopeEnd);
        }));
    }

    private static void emitScalar(CodeBuilder cob, ClassDesc thisClass, int gen,
            String nameEntry, String handleEntry, String helper,
            MethodTypeDesc helperType, ClassDesc erasedDesc) {
        cob.aload(gen);
        ldcData(cob, nameEntry, CD_SERIALIZABLE_STRING);
        emitLoad(cob, handleEntry, erasedDesc);
        cob.invokestatic(thisClass, helper, helperType);
    }

    // Loads the property value from the bean (parameter 1) through the
    // constant (Object)eV handle.
    private static void emitLoad(CodeBuilder cob, String handleEntry, ClassDesc erasedDesc) {
        ldcData(cob, handleEntry, ConstantDescs.CD_MethodHandle);
        cob.aload(1);
        cob.invokevirtual(ConstantDescs.CD_MethodHandle, "invokeExact",
                MethodTypeDesc.of(erasedDesc, ConstantDescs.CD_Object));
    }

    private static void emitNullableRef(CodeBuilder cob, int gen, int slot, Runnable nonNull) {
        Label isNull = cob.newLabel();
        Label done = cob.newLabel();
        cob.aload(slot).ifnull(isNull);
        nonNull.run();
        cob.goto_(done);
        cob.labelBinding(isNull);
        cob.aload(gen).invokevirtual(CD_JSON_GENERATOR, "writeNull", MTD_WRITE_NULL).pop();
        cob.labelBinding(done);
    }
}
